import dotenv from "dotenv";
dotenv.config();

export const env = {

  KIOT: {
    KIOTVIET_RETAILER: process.env.KIOTVIET_RETAILER,
    KIOTVIET_CLIENT_ID: process.env.KIOT_CLIENT_ID,
    KIOTVIET_CLIENT_SECRET: process.env.KIOT_SECRET,
  },

  SUPABASE: {
    SERVICE_KEY: process.env.DATABASE_SERVICE_KEY,
  },

  LARK: {
    APP_ID: process.env.LARK_APP_ID,
    APP_SECRET: process.env.LARK_APP_SECRET,
    BASE_ID: process.env.LARK_BASE_ID,
    TABLE_PRODUCT_NAME: process.env.LARK_TABLE_PRODUCT_NAME,
    TABLE_INVOICES_NAME: process.env.LARK_TABLE_INVOICE_NAME,
    TABLE_INVOICES_DETAIL_NAME: process.env.LARK_TABLE_INVOICE_DETAIL_NAME,
    TABLE_INVOICE__FROM: process.env.LARK_TABLE_INVOICE__FROM,
    TABLE_INVOICE__TO: process.env.LARK_TABLE_INVOICE__TO,
    TABLE_CUSTOMER_NAME: process.env.LARK_TABLE_CUSTOMER_NAME,
    TABLE_RETURN_NAME: process.env.LARK_TABLE_RETURN_NAME,
    TABLE_RETURN_DETAILS_NAME: process.env.LARK_TABLE_RETURN_DETAILS_NAME,
    TABLE_CASHFLOW_NAME: process.env.LARK_TABLE_CASHFLOW_NAME,
    TABLE_SUPPLIERS_NAME: process.env.LARK_TABLE_SUPPLIERS_NAME,
  },

  AES_256_CBC: {
    APP_SECRET_KEY: process.env.AES_256_CBC_APP_SECRET_KEY,
  },
};
